"""adds customer  model

Revision ID: 50db8e9a2a35
Revises: d177b34e3140
Create Date: 2021-05-18 18:39:48.763428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50db8e9a2a35'
down_revision = 'd177b34e3140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
