"""adds video model

Revision ID: 9d9a06481885
Revises: 9e13e188f0e1
Create Date: 2021-05-19 18:14:01.039487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d9a06481885'
down_revision = '9e13e188f0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental')
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    op.create_table('rental',
    sa.Column('rental_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='rental_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], name='rental_video_id_fkey'),
    sa.PrimaryKeyConstraint('rental_id', name='rental_pkey')
    )
    # ### end Alembic commands ###
