"""adds video  model

Revision ID: e28d3e300687
Revises: cd9fd5136e7e
Create Date: 2021-05-18 13:41:45.662075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e28d3e300687'
down_revision = 'cd9fd5136e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('video', 'video_title')
    op.drop_column('video', 'video_total_inventory')
    op.drop_column('video', 'video_release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('video_total_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('video_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'title')
    op.drop_column('video', 'release_date')
    # ### end Alembic commands ###
